import type { Theme, ThemeId } from './types';

/**
 * 21 refined themes. All procedural (no assets), all system fonts
 * (canvas export never misses a webfont). Design notes:
 * - Charmera shots exactly fill their cell, so differentiation lives in
 *   the MAT (frame around each photo) and the GUTTERS.
 * - Gaps are generous so the background breathes through.
 */
export const THEMES: Record<ThemeId, Theme> = {
  darkroom: {
    id: 'darkroom', name: 'Darkroom', tagline: 'Classic contact sheet', category: 'Dark',
    bg: ['#0b0705', '#1c0f0a'], cellBg: '#000000',
    gap: 48, outerPad: 114, radius: 2, captionHeight: 110,
    captionFont: '600 44px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    captionColor: '#f5ead2', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#0b0705,#7f1d1d)',
    borderColor: '#efe6d0', borderWidth: 4, shadow: false, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(245,234,210,0.4)',
    framed: true,
    mat: 12, matBottom: 12,
  },
  polaroid: {
    id: 'polaroid', name: 'Polaroid Fun', tagline: 'Thick cream + wiggle', category: 'Retro',
    bg: ['#f5efe0', '#e9dcc2'], cellBg: '#fffdf5',
    gap: 80, outerPad: 124, radius: 10, captionHeight: 150,
    captionFont: 'italic 52px "Comic Sans MS", "Segoe Print", "Bradley Hand", cursive',
    captionColor: '#5b4a3a', captionBg: null,
    grain: false, vignette: false, jitterDeg: 1.8,
    swatch: 'linear-gradient(135deg,#fffdf5,#e7d8b7)',
    borderColor: '#d8c9a8', borderWidth: 2, shadow: true, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(91,74,58,0.45)',
    framed: true,
    mat: 44, matBottom: 44,
  },
  gallery: {
    id: 'gallery', name: 'Cream Gallery', tagline: 'Calm museum wall', category: 'Elegant',
    bg: ['#faf7f0', '#efe7d6'], cellBg: '#ffffff',
    gap: 96, outerPad: 162, radius: 4, captionHeight: 130,
    captionFont: 'italic 46px Georgia, "Times New Roman", serif',
    captionColor: '#3d3a34', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#faf7f0,#d9cfb8)',
    borderColor: '#e2d9c4', borderWidth: 2, shadow: true, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(61,58,52,0.4)',
    framed: true,
    mat: 20, matBottom: 20,
  },
  y2k: {
    id: 'y2k', name: 'Y2K Chrome', tagline: 'Millennium shiny', category: 'Retro',
    bg: ['#dfe6f5', '#aeb9d6', '#e8edf9'], cellBg: '#0b1020',
    gap: 54, outerPad: 116, radius: 18, captionHeight: 120,
    captionFont: '700 44px "Courier New", ui-monospace, monospace',
    captionColor: '#00f0ff', captionBg: '#0b1020',
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#aeb9d6,#00f0ff)',
    borderColor: '#7dd3fc', borderWidth: 3, shadow: false, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(0,240,255,0.4)',
    framed: true,
    mat: 12, matBottom: 12,
  },
  playground: {
    id: 'playground', name: 'Playground', tagline: 'Bold + bouncy', category: 'Playful',
    bg: ['#ffd93d', '#ff8fab', '#6bcbff'], cellBg: '#ffffff',
    gap: 68, outerPad: 128, radius: 28, captionHeight: 130,
    captionFont: '800 50px Verdana, system-ui, sans-serif',
    captionColor: '#1c1c1e', captionBg: '#ffffff',
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#ffd93d,#ff8fab)',
    borderColor: '#1c1c1e', borderWidth: 4, shadow: true, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(28,28,30,0.4)',
    framed: true,
    mat: 24, matBottom: 24,
  },
  'midnight-neon': {
    id: 'midnight-neon', name: 'Midnight Neon', tagline: 'City lights after dark', category: 'Dark',
    bg: ['#070b1a', '#101b3d'], cellBg: '#0c1226',
    gap: 52, outerPad: 118, radius: 16, captionHeight: 120,
    captionFont: '700 44px ui-monospace, SFMono-Regular, Menlo, monospace',
    captionColor: '#7df9ff', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#070b1a,#2547ff)',
    borderColor: '#2b3f8f', borderWidth: 2, shadow: false, texture: 'dots',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(125,249,255,0.4)',
    framed: true,
    mat: 12, matBottom: 12,
  },
  espresso: {
    id: 'espresso', name: 'Espresso', tagline: 'Warm coffee-house brown', category: 'Elegant',
    bg: ['#2a1c12', '#4a2f1d'], cellBg: '#faf3e8',
    gap: 76, outerPad: 144, radius: 12, captionHeight: 130,
    captionFont: '46px Georgia, "Times New Roman", serif',
    captionColor: '#4a2f1d', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#2a1c12,#a9744f)',
    borderColor: '#8a6647', borderWidth: 2, shadow: false, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(250,243,232,0.4)',
    framed: true,
    mat: 24, matBottom: 24,
  },
  forest: {
    id: 'forest', name: 'Forest Walk', tagline: 'Moss + pine quiet', category: 'Nature',
    bg: ['#1c2b1f', '#33482f'], cellBg: '#f4f1e4',
    gap: 72, outerPad: 132, radius: 20, captionHeight: 130,
    captionFont: 'italic 48px Georgia, serif',
    captionColor: '#2c3a24', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#1c2b1f,#7a9b57)',
    borderColor: '#5c7350', borderWidth: 2, shadow: false, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(244,241,228,0.45)',
    framed: true,
    mat: 20, matBottom: 20,
  },
  ocean: {
    id: 'ocean', name: 'Ocean Postcard', tagline: 'Salt air + deep blue', category: 'Nature',
    bg: ['#0a2e4f', '#1286a8'], cellBg: '#f2f8fa',
    gap: 62, outerPad: 128, radius: 22, captionHeight: 125,
    captionFont: '700 46px Verdana, system-ui, sans-serif',
    captionColor: '#0a2e4f', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#0a2e4f,#5fd4d0)',
    borderColor: '#bfe3e8', borderWidth: 3, shadow: true, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(242,248,250,0.5)',
    framed: true,
    mat: 16, matBottom: 16,
  },
  desert: {
    id: 'desert', name: 'Desert Sun', tagline: 'Sand + terracotta heat', category: 'Nature',
    bg: ['#e8b04b', '#c96f2f'], cellBg: '#fdf6e3',
    gap: 68, outerPad: 136, radius: 14, captionHeight: 130,
    captionFont: '700 46px Georgia, serif',
    captionColor: '#7c3f12', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#e8b04b,#8f3b12)',
    borderColor: '#a85f28', borderWidth: 2, shadow: true, texture: 'dots',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(124,63,18,0.4)',
    framed: true,
    mat: 20, matBottom: 20,
  },
  sakura: {
    id: 'sakura', name: 'Sakura', tagline: 'Soft pink blossom', category: 'Light',
    bg: ['#fdf0f3', '#f6cdd8'], cellBg: '#ffffff',
    gap: 76, outerPad: 138, radius: 24, captionHeight: 130,
    captionFont: 'italic 48px Georgia, serif',
    captionColor: '#8f3b56', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#fdf0f3,#e89bb4)',
    borderColor: '#e5aec0', borderWidth: 2, shadow: true, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(143,59,86,0.4)',
    framed: true,
    mat: 24, matBottom: 24,
  },
  'mono-ink': {
    id: 'mono-ink', name: 'Mono Ink', tagline: 'Strict black + white', category: 'Elegant',
    bg: ['#f4f4f4', '#d9d9d9'], cellBg: '#111111',
    gap: 44, outerPad: 108, radius: 2, captionHeight: 110,
    captionFont: '600 42px Helvetica, Arial, sans-serif',
    captionColor: '#f4f4f4', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#111111 50%,#f4f4f4 50%)',
    borderColor: '#111111', borderWidth: 3, shadow: false, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(17,17,17,0.4)',
    framed: true,
    mat: 10, matBottom: 10,
  },
  blueprint: {
    id: 'blueprint', name: 'Blueprint', tagline: 'Drafting-table blue', category: 'Retro',
    bg: ['#123a6d', '#1d5aa8'], cellBg: '#0e2c55',
    gap: 52, outerPad: 116, radius: 4, captionHeight: 115,
    captionFont: '500 42px "Courier New", ui-monospace, monospace',
    captionColor: '#d6e7ff', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#123a6d,#5aa2f0)',
    borderColor: '#9cc3ee', borderWidth: 2, shadow: false, texture: 'dots',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(214,231,255,0.45)',
    framed: true,
    mat: 12, matBottom: 12,
  },
  newsprint: {
    id: 'newsprint', name: 'Newsprint', tagline: 'Morning-paper columns', category: 'Retro',
    bg: ['#ece5d3', '#d9cfb4'], cellBg: '#faf8f0',
    gap: 46, outerPad: 122, radius: 2, captionHeight: 120,
    captionFont: '700 40px Georgia, "Times New Roman", serif',
    captionColor: '#222222', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#ece5d3,#8a8271)',
    borderColor: '#8a8271', borderWidth: 2, shadow: false, texture: 'stripes',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(34,34,34,0.4)',
    framed: true,
    mat: 8, matBottom: 8,
  },
  noir: {
    id: 'noir', name: 'Noir Cinema', tagline: 'Black-bar movie stills', category: 'Dark',
    bg: ['#000000', '#161616'], cellBg: '#000000',
    gap: 58, outerPad: 136, radius: 2, captionHeight: 120,
    captionFont: '500 44px Helvetica, Arial, sans-serif',
    captionColor: '#e8e4d8', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#000000,#4d4d4d)',
    borderColor: '#333333', borderWidth: 2, shadow: false, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(232,228,216,0.4)',
    framed: true,
    mat: 14, matBottom: 14,
  },
  disco: {
    id: 'disco', name: 'Disco Fever', tagline: 'Mirror-ball purple', category: 'Playful',
    bg: ['#2b0a4e', '#7b2ff7', '#f107a3'], cellBg: '#14082b',
    gap: 56, outerPad: 122, radius: 20, captionHeight: 125,
    captionFont: '800 46px Verdana, system-ui, sans-serif',
    captionColor: '#ffd6f5', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#2b0a4e,#f107a3)',
    borderColor: '#c86bfa', borderWidth: 3, shadow: false, texture: 'dots',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(255,214,245,0.45)',
    framed: true,
    mat: 12, matBottom: 12,
  },
  candy: {
    id: 'candy', name: 'Candy Pop', tagline: 'Bubblegum bright', category: 'Playful',
    bg: ['#ffe3ec', '#ffc2d8'], cellBg: '#ffffff',
    gap: 72, outerPad: 130, radius: 30, captionHeight: 130,
    captionFont: '800 48px "Comic Sans MS", "Chalkboard SE", cursive',
    captionColor: '#c2185b', captionBg: null,
    grain: false, vignette: false, jitterDeg: 1.2,
    swatch: 'linear-gradient(135deg,#ffc2d8,#ff5c9d)',
    borderColor: '#ff8fb8', borderWidth: 3, shadow: true, texture: 'dots',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(194,24,91,0.4)',
    framed: true,
    mat: 32, matBottom: 32,
  },
  pastel: {
    id: 'pastel', name: 'Pastel Dream', tagline: 'Cloud-soft haze', category: 'Light',
    bg: ['#e6e6fa', '#cfe8ef', '#fde8ef'], cellBg: '#ffffff',
    gap: 84, outerPad: 150, radius: 26, captionHeight: 125,
    captionFont: 'italic 46px Georgia, serif',
    captionColor: '#6b6b8f', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#cfe8ef,#fde8ef)',
    borderColor: '#cfcfe8', borderWidth: 2, shadow: true, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(107,107,143,0.4)',
    framed: true,
    mat: 28, matBottom: 28,
  },
  bauhaus: {
    id: 'bauhaus', name: 'Bauhaus', tagline: 'Primary shapes only', category: 'Playful',
    bg: ['#f2efe6', '#e2dccb'], cellBg: '#ffffff',
    gap: 52, outerPad: 118, radius: 2, captionHeight: 120,
    captionFont: '800 44px Helvetica, Arial, sans-serif',
    captionColor: '#1a1a1a', captionBg: '#f2efe6',
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#e30613 33%,#f5d90a 33% 66%,#0066b3 66%)',
    borderColor: '#1a1a1a', borderWidth: 5, shadow: false, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(26,26,26,0.4)',
    framed: true,
    mat: 36, matBottom: 36,
  },
  chalkboard: {
    id: 'chalkboard', name: 'Chalkboard', tagline: 'Classroom chalk dust', category: 'Dark',
    bg: ['#1e2b26', '#2e4038'], cellBg: '#223028',
    gap: 62, outerPad: 128, radius: 8, captionHeight: 130,
    captionFont: '52px "Comic Sans MS", "Segoe Print", cursive',
    captionColor: '#f5f2e4', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#1e2b26,#7fa393)',
    borderColor: '#c9a86a', borderWidth: 6, shadow: false, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(245,242,228,0.4)',
    framed: true,
    mat: 28, matBottom: 28,
  },
  golden: {
    id: 'golden', name: 'Golden Hour', tagline: 'Warm sunset glow', category: 'Nature',
    bg: ['#3a1c4f', '#c96f2f', '#f2b544'], cellBg: '#1f1029',
    gap: 58, outerPad: 128, radius: 18, captionHeight: 125,
    captionFont: 'italic 48px Georgia, serif',
    captionColor: '#ffe3a3', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#3a1c4f,#f2b544)',
    borderColor: '#e8a33d', borderWidth: 2, shadow: false, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(255,227,163,0.45)',
    framed: true,
    mat: 16, matBottom: 16,
  },
  'pop-art': {
    id: 'pop-art', name: 'Pop Art', tagline: 'Comic-print POW', category: 'Playful',
    bg: ['#ffd500', '#ff8a00'], cellBg: '#ffffff',
    gap: 64, outerPad: 120, radius: 8, captionHeight: 135,
    captionFont: '900 52px "Arial Black", Verdana, sans-serif',
    captionColor: '#111111', captionBg: '#ffffff',
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#ffd500,#e30613)',
    borderColor: '#111111', borderWidth: 6, shadow: true, texture: 'halftone',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(17,17,17,0.45)',
    framed: true,
    mat: 16, matBottom: 16,
  },
  sunburst: {
    id: 'sunburst', name: 'Sunburst', tagline: 'Retro carnival rays', category: 'Playful',
    bg: ['#c1440e', '#e8a33d'], cellBg: '#fdf3e0',
    gap: 68, outerPad: 124, radius: 24, captionHeight: 130,
    captionFont: '800 50px Verdana, system-ui, sans-serif',
    captionColor: '#7c3f12', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#c1440e,#f2d06b)',
    borderColor: '#7c3f12', borderWidth: 3, shadow: true, texture: 'rays',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(124,63,18,0.45)',
    framed: true,
    mat: 20, matBottom: 20,
  },
  linen: {
    id: 'linen', name: 'Linen', tagline: 'Quiet woven luxury', category: 'Elegant',
    bg: ['#e8e4da', '#d5cfc0'], cellBg: '#fbfaf6',
    gap: 84, outerPad: 140, radius: 6, captionHeight: 130,
    captionFont: '46px Georgia, "Times New Roman", serif',
    captionColor: '#4a4438', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#e8e4da,#a89f8c)',
    borderColor: '#b8b0a0', borderWidth: 2, shadow: true, texture: 'weave',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(74,68,56,0.4)',
    framed: true,
    mat: 24, matBottom: 24,
  },
  starry: {
    id: 'starry', name: 'Starry Night', tagline: 'Deep field + sparks', category: 'Dark',
    bg: ['#060a24', '#14204d'], cellBg: '#0a1030',
    gap: 56, outerPad: 120, radius: 14, captionHeight: 120,
    captionFont: '600 44px ui-monospace, SFMono-Regular, Menlo, monospace',
    captionColor: '#cfe0ff', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#060a24,#3a5fd0)',
    borderColor: '#3a4f9e', borderWidth: 2, shadow: false, texture: 'stars',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(207,224,255,0.4)',
    framed: true,
    mat: 12, matBottom: 12,
  },
  confetti: {
    id: 'confetti', name: 'Confetti Cream', tagline: 'Party sprinkles', category: 'Playful',
    bg: ['#faf5ea', '#f0e4cc'], cellBg: '#ffffff',
    gap: 76, outerPad: 126, radius: 30, captionHeight: 130,
    captionFont: '800 48px "Comic Sans MS", "Chalkboard SE", cursive',
    captionColor: '#333333', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#faf5ea,#ff8fab)',
    borderColor: '#e0cfa8', borderWidth: 3, shadow: true, texture: 'sprinkles',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(51,51,51,0.4)',
    framed: true,
    mat: 28, matBottom: 28,
  },
  terrazzo: {
    id: 'terrazzo', name: 'Terrazzo', tagline: 'Stone-chip chic', category: 'Light',
    bg: ['#f2efe4', '#e4d9c6'], cellBg: '#fbf9f3',
    gap: 72, outerPad: 130, radius: 18, captionHeight: 125,
    captionFont: 'italic 46px Georgia, serif',
    captionColor: '#5a5248', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#f2efe4,#a89070)',
    borderColor: '#c9bda6', borderWidth: 2, shadow: true, texture: 'terrazzo',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(90,82,72,0.4)',
    framed: true,
    mat: 22, matBottom: 22,
  },
  studio: {
    id: 'studio', name: 'Studio Wall', tagline: 'Drafting-grid calm', category: 'Retro',
    bg: ['#dde3da', '#b9c4b4'], cellBg: '#f4f6f2',
    gap: 60, outerPad: 122, radius: 4, captionHeight: 115,
    captionFont: '500 42px "Courier New", ui-monospace, monospace',
    captionColor: '#2e3a30', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#dde3da,#5f6f62)',
    borderColor: '#5f6f62', borderWidth: 3, shadow: false, texture: 'grid',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(46,58,48,0.4)',
    framed: true,
    mat: 14, matBottom: 14,
  },
  ember: {
    id: 'ember', name: 'Ember', tagline: 'Darkroom light leak', category: 'Dark',
    bg: ['#0d0505', '#241012'], cellBg: '#120808',
    gap: 52, outerPad: 118, radius: 12, captionHeight: 120,
    captionFont: '700 44px ui-monospace, SFMono-Regular, Menlo, monospace',
    captionColor: '#ffb37a', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#0d0505,#ff6e1e)',
    borderColor: '#6e2f16', borderWidth: 2, shadow: false, texture: 'lightleak',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(255,179,122,0.4)',
    framed: true,
    mat: 12, matBottom: 12,
  },
  dusk: {
    id: 'dusk', name: 'Dusk', tagline: 'Sunset spotlight', category: 'Nature',
    bg: ['#f2a65a', '#7b4b94', '#2b2350'], cellBg: '#1d1836',
    gap: 58, outerPad: 124, radius: 20, captionHeight: 125,
    captionFont: 'italic 48px Georgia, serif',
    captionColor: '#ffd9a3', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'radial-gradient(circle,#f2a65a,#2b2350)',
    borderColor: '#8a5f9e', borderWidth: 2, shadow: false, texture: 'none',
    bgStyle: 'radial',
    textureColor: null,
    placeholderColor: 'rgba(255,217,163,0.4)',
    framed: true,
    mat: 14, matBottom: 14,
  },
  kraft: {
    id: 'kraft', name: 'Kraft Paper', tagline: 'Stamped + fibrous', category: 'Retro',
    bg: ['#b98d5e', '#8f6640'], cellBg: '#f6eeda',
    gap: 66, outerPad: 124, radius: 4, captionHeight: 125,
    captionFont: '700 44px "Courier New", ui-monospace, monospace',
    captionColor: '#4a2f1d', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#c49a68,#5a3a20)',
    borderColor: '#5a3a20', borderWidth: 3, shadow: true, texture: 'fiber',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(74,47,29,0.45)',
    framed: true,
    mat: 18, matBottom: 18,
  },
  soda: {
    id: 'soda', name: 'Soda Shop', tagline: 'Cherry-checker pop', category: 'Retro',
    bg: ['#f6efe2', '#e8d9bd'], cellBg: '#ffffff',
    gap: 60, outerPad: 120, radius: 16, captionHeight: 125,
    captionFont: '800 46px Verdana, system-ui, sans-serif',
    captionColor: '#c1272d', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#f6efe2,#c1272d)',
    borderColor: '#c1272d', borderWidth: 4, shadow: true, texture: 'checker',
    bgStyle: 'linear',
    textureColor: 'rgba(193,39,45,0.08)',
    placeholderColor: 'rgba(193,39,45,0.45)',
    framed: true,
    mat: 18, matBottom: 18,
  },
  tuxedo: {
    id: 'tuxedo', name: 'Tuxedo', tagline: 'Pinstripe formal', category: 'Elegant',
    bg: ['#0c0c0e', '#232326'], cellBg: '#101012',
    gap: 56, outerPad: 128, radius: 4, captionHeight: 120,
    captionFont: '500 44px Georgia, "Times New Roman", serif',
    captionColor: '#e8e2d2', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#0c0c0e,#8a8578)',
    borderColor: '#c9bfa8', borderWidth: 2, shadow: false, texture: 'stripes',
    bgStyle: 'linear',
    textureColor: 'rgba(255,255,255,0.09)',
    placeholderColor: 'rgba(232,226,210,0.4)',
    framed: true,
    mat: 14, matBottom: 14,
  },
  nautical: {
    id: 'nautical', name: 'Nautical', tagline: 'Deck stripes', category: 'Nature',
    bg: ['#0e2a4a', '#1d5a8a'], cellBg: '#f2f6f8',
    gap: 62, outerPad: 122, radius: 20, captionHeight: 125,
    captionFont: '700 46px Verdana, system-ui, sans-serif',
    captionColor: '#0e2a4a', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#0e2a4a,#5fa8d0)',
    borderColor: '#dfe9ee', borderWidth: 3, shadow: true, texture: 'stripes',
    bgStyle: 'linear',
    textureColor: 'rgba(255,255,255,0.10)',
    placeholderColor: 'rgba(242,246,248,0.5)',
    framed: true,
    mat: 16, matBottom: 16,
  },
  matcha: {
    id: 'matcha', name: 'Matcha', tagline: 'Green-tea calm', category: 'Nature',
    bg: ['#7a9b57', '#4a6b35'], cellBg: '#f4f2e4',
    gap: 70, outerPad: 126, radius: 22, captionHeight: 130,
    captionFont: 'italic 48px Georgia, serif',
    captionColor: '#33471f', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#7a9b57,#33471f)',
    borderColor: '#3c5228', borderWidth: 2, shadow: true, texture: 'fiber',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(51,71,31,0.45)',
    framed: true,
    mat: 20, matBottom: 20,
  },
  royal: {
    id: 'royal', name: 'Royal', tagline: 'Velvet + gold', category: 'Elegant',
    bg: ['#e8c96a', '#6b2d8f', '#241040'], cellBg: '#1c1030',
    gap: 60, outerPad: 134, radius: 10, captionHeight: 130,
    captionFont: '46px Georgia, "Times New Roman", serif',
    captionColor: '#f0d98a', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'radial-gradient(circle,#e8c96a,#241040)',
    borderColor: '#c9a227', borderWidth: 3, shadow: false, texture: 'none',
    bgStyle: 'radial',
    textureColor: null,
    placeholderColor: 'rgba(240,217,138,0.4)',
    framed: true,
    mat: 16, matBottom: 16,
  },
  seamless: {
    id: 'seamless', name: 'Seamless', tagline: 'Continuity-first calm', category: 'Light',
    bg: ['#e9e6de', '#d8d3c6'], cellBg: '#f7f5ef',
    gap: 72, outerPad: 130, radius: 12, captionHeight: 125,
    captionFont: 'italic 46px Georgia, serif',
    captionColor: '#55504a', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#e9e6de,#b8b2a4)',
    borderColor: '#c4bcab', borderWidth: 2, shadow: false, texture: 'fiber',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(85,80,74,0.4)',
    framed: true,
    mat: 4, matBottom: 4,
  },
  float: {
    id: 'float', name: 'Float', tagline: 'Gallery air, no frame', category: 'Light',
    bg: ['#fafafa', '#ececec'], cellBg: '#ffffff',
    gap: 84, outerPad: 150, radius: 24, captionHeight: 125,
    captionFont: '46px system-ui, sans-serif',
    captionColor: '#555555', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#ffffff,#cfcfcf)',
    borderColor: null, borderWidth: 0, shadow: true, texture: 'none',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(85,85,85,0.4)',
    framed: false,
    mat: 0, matBottom: 0,
  },
  'night-float': {
    id: 'night-float', name: 'Night Float', tagline: 'Lift out of the dark', category: 'Dark',
    bg: ['#08080c', '#17171f'], cellBg: '#101014',
    gap: 84, outerPad: 150, radius: 24, captionHeight: 125,
    captionFont: '46px system-ui, sans-serif',
    captionColor: '#cccccc', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#08080c,#3a3a55)',
    borderColor: null, borderWidth: 0, shadow: true, texture: 'stars',
    bgStyle: 'linear',
    textureColor: null,
    placeholderColor: 'rgba(204,204,204,0.4)',
    framed: false,
    mat: 0, matBottom: 0,
  },
  sticker: {
    id: 'sticker', name: 'Sticker Book', tagline: 'Die-cut gloss', category: 'Playful',
    bg: ['#d8ecff', '#ffe3ef'], cellBg: '#ffffff',
    gap: 72, outerPad: 130, radius: 48, captionHeight: 130,
    captionFont: '800 50px Verdana, system-ui, sans-serif',
    captionColor: '#333333', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#d8ecff,#ff8fb8)',
    borderColor: '#ff5c9d', borderWidth: 5, shadow: true, texture: 'dots',
    bgStyle: 'linear',
    textureColor: 'rgba(255,255,255,0.5)',
    placeholderColor: 'rgba(51,51,51,0.4)',
    framed: true,
    mat: 56, matBottom: 64,
  },
};

export const THEME_LIST: Theme[] = [
  THEMES.darkroom, THEMES.polaroid, THEMES.gallery, THEMES.y2k, THEMES.playground,
  THEMES['midnight-neon'], THEMES.espresso, THEMES.forest, THEMES.ocean, THEMES.desert,
  THEMES.sakura, THEMES['mono-ink'], THEMES.blueprint, THEMES.newsprint, THEMES.noir,
  THEMES.disco, THEMES.candy, THEMES.pastel, THEMES.bauhaus, THEMES.chalkboard, THEMES.golden,
  THEMES['pop-art'], THEMES.sunburst, THEMES.linen, THEMES.starry, THEMES.confetti,
  THEMES.terrazzo, THEMES.studio, THEMES.ember, THEMES.dusk, THEMES.kraft,
  THEMES.soda, THEMES.tuxedo, THEMES.nautical, THEMES.matcha, THEMES.royal,
  THEMES.seamless, THEMES.float, THEMES['night-float'], THEMES.sticker,
];

export const THEME_CATEGORIES = ['All', 'Dark', 'Light', 'Retro', 'Playful', 'Elegant', 'Nature'] as const;
export type ThemeCategoryFilter = (typeof THEME_CATEGORIES)[number];
