import type { Theme, ThemeId } from './types';

/**
 * 21 refined themes. All procedural (no assets), all system fonts
 * (canvas export never misses a webfont). Each theme tuned for:
 * - caption legibility on its own card
 * - consistent gap / pad / radius rhythm
 * - subtle texture (grain / vignette / pattern / jitter) matched to mood
 */
export const THEMES: Record<ThemeId, Theme> = {
  darkroom: {
    id: 'darkroom', name: 'Darkroom', tagline: 'Contact-sheet red glow', category: 'Dark',
    bg: ['#160404', '#2b0a0a'], cellBg: '#0e0202',
    gap: 28, outerPad: 72, radius: 6, captionHeight: 110,
    captionFont: '600 44px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
    captionColor: '#ffd9d9', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#160404,#7f1d1d)',
    borderColor: '#4a1515', borderWidth: 2, shadow: false, pattern: 'none',
    placeholderColor: 'rgba(255,217,217,0.4)',
  },
  polaroid: {
    id: 'polaroid', name: 'Polaroid Fun', tagline: 'Thick cream + wiggle', category: 'Retro',
    bg: ['#f5efe0', '#e9dcc2'], cellBg: '#fffdf5',
    gap: 48, outerPad: 80, radius: 10, captionHeight: 150,
    captionFont: 'italic 52px "Comic Sans MS", "Segoe Print", "Bradley Hand", cursive',
    captionColor: '#5b4a3a', captionBg: null,
    grain: false, vignette: false, jitterDeg: 1.8,
    swatch: 'linear-gradient(135deg,#fffdf5,#e7d8b7)',
    borderColor: '#d8c9a8', borderWidth: 2, shadow: true, pattern: 'none',
    placeholderColor: 'rgba(91,74,58,0.45)',
  },
  gallery: {
    id: 'gallery', name: 'Cream Gallery', tagline: 'Calm museum wall', category: 'Elegant',
    bg: ['#faf7f0', '#efe7d6'], cellBg: '#ffffff',
    gap: 56, outerPad: 110, radius: 4, captionHeight: 130,
    captionFont: 'italic 46px Georgia, "Times New Roman", serif',
    captionColor: '#3d3a34', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#faf7f0,#d9cfb8)',
    borderColor: '#e2d9c4', borderWidth: 2, shadow: true, pattern: 'none',
    placeholderColor: 'rgba(61,58,52,0.4)',
  },
  y2k: {
    id: 'y2k', name: 'Y2K Chrome', tagline: 'Millennium shiny', category: 'Retro',
    bg: ['#dfe6f5', '#aeb9d6', '#e8edf9'], cellBg: '#0b1020',
    gap: 32, outerPad: 76, radius: 18, captionHeight: 120,
    captionFont: '700 44px "Courier New", ui-monospace, monospace',
    captionColor: '#00f0ff', captionBg: '#0b1020',
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#aeb9d6,#00f0ff)',
    borderColor: '#7dd3fc', borderWidth: 3, shadow: false, pattern: 'none',
    placeholderColor: 'rgba(0,240,255,0.4)',
  },
  playground: {
    id: 'playground', name: 'Playground', tagline: 'Bold + bouncy', category: 'Playful',
    bg: ['#ffd93d', '#ff8fab', '#6bcbff'], cellBg: '#ffffff',
    gap: 40, outerPad: 84, radius: 28, captionHeight: 130,
    captionFont: '800 50px Verdana, system-ui, sans-serif',
    captionColor: '#1c1c1e', captionBg: '#ffffff',
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#ffd93d,#ff8fab)',
    borderColor: '#1c1c1e', borderWidth: 4, shadow: true, pattern: 'none',
    placeholderColor: 'rgba(28,28,30,0.4)',
  },
  'midnight-neon': {
    id: 'midnight-neon', name: 'Midnight Neon', tagline: 'City lights after dark', category: 'Dark',
    bg: ['#070b1a', '#101b3d'], cellBg: '#0c1226',
    gap: 30, outerPad: 78, radius: 16, captionHeight: 120,
    captionFont: '700 44px ui-monospace, SFMono-Regular, Menlo, monospace',
    captionColor: '#7df9ff', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#070b1a,#2547ff)',
    borderColor: '#2b3f8f', borderWidth: 2, shadow: false, pattern: 'dots',
    placeholderColor: 'rgba(125,249,255,0.4)',
  },
  espresso: {
    id: 'espresso', name: 'Espresso', tagline: 'Warm coffee-house brown', category: 'Elegant',
    bg: ['#2a1c12', '#4a2f1d'], cellBg: '#faf3e8',
    gap: 44, outerPad: 96, radius: 12, captionHeight: 130,
    captionFont: '46px Georgia, "Times New Roman", serif',
    captionColor: '#4a2f1d', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#2a1c12,#a9744f)',
    borderColor: '#8a6647', borderWidth: 2, shadow: false, pattern: 'none',
    placeholderColor: 'rgba(250,243,232,0.4)',
  },
  forest: {
    id: 'forest', name: 'Forest Walk', tagline: 'Moss + pine quiet', category: 'Nature',
    bg: ['#1c2b1f', '#33482f'], cellBg: '#f4f1e4',
    gap: 42, outerPad: 88, radius: 20, captionHeight: 130,
    captionFont: 'italic 48px Georgia, serif',
    captionColor: '#2c3a24', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#1c2b1f,#7a9b57)',
    borderColor: '#5c7350', borderWidth: 2, shadow: false, pattern: 'none',
    placeholderColor: 'rgba(244,241,228,0.45)',
  },
  ocean: {
    id: 'ocean', name: 'Ocean Postcard', tagline: 'Salt air + deep blue', category: 'Nature',
    bg: ['#0a2e4f', '#1286a8'], cellBg: '#f2f8fa',
    gap: 36, outerPad: 84, radius: 22, captionHeight: 125,
    captionFont: '700 46px Verdana, system-ui, sans-serif',
    captionColor: '#0a2e4f', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#0a2e4f,#5fd4d0)',
    borderColor: '#bfe3e8', borderWidth: 3, shadow: true, pattern: 'none',
    placeholderColor: 'rgba(242,248,250,0.5)',
  },
  desert: {
    id: 'desert', name: 'Desert Sun', tagline: 'Sand + terracotta heat', category: 'Nature',
    bg: ['#e8b04b', '#c96f2f'], cellBg: '#fdf6e3',
    gap: 40, outerPad: 90, radius: 14, captionHeight: 130,
    captionFont: '700 46px Georgia, serif',
    captionColor: '#7c3f12', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#e8b04b,#8f3b12)',
    borderColor: '#a85f28', borderWidth: 2, shadow: true, pattern: 'dots',
    placeholderColor: 'rgba(124,63,18,0.4)',
  },
  sakura: {
    id: 'sakura', name: 'Sakura', tagline: 'Soft pink blossom', category: 'Light',
    bg: ['#fdf0f3', '#f6cdd8'], cellBg: '#ffffff',
    gap: 44, outerPad: 92, radius: 24, captionHeight: 130,
    captionFont: 'italic 48px Georgia, serif',
    captionColor: '#8f3b56', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#fdf0f3,#e89bb4)',
    borderColor: '#e5aec0', borderWidth: 2, shadow: true, pattern: 'none',
    placeholderColor: 'rgba(143,59,86,0.4)',
  },
  'mono-ink': {
    id: 'mono-ink', name: 'Mono Ink', tagline: 'Strict black + white', category: 'Elegant',
    bg: ['#f4f4f4', '#d9d9d9'], cellBg: '#111111',
    gap: 24, outerPad: 70, radius: 2, captionHeight: 110,
    captionFont: '600 42px Helvetica, Arial, sans-serif',
    captionColor: '#f4f4f4', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#111111 50%,#f4f4f4 50%)',
    borderColor: '#111111', borderWidth: 3, shadow: false, pattern: 'none',
    placeholderColor: 'rgba(17,17,17,0.4)',
  },
  blueprint: {
    id: 'blueprint', name: 'Blueprint', tagline: 'Drafting-table blue', category: 'Retro',
    bg: ['#123a6d', '#1d5aa8'], cellBg: '#0e2c55',
    gap: 30, outerPad: 76, radius: 4, captionHeight: 115,
    captionFont: '500 42px "Courier New", ui-monospace, monospace',
    captionColor: '#d6e7ff', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#123a6d,#5aa2f0)',
    borderColor: '#9cc3ee', borderWidth: 2, shadow: false, pattern: 'dots',
    placeholderColor: 'rgba(214,231,255,0.45)',
  },
  newsprint: {
    id: 'newsprint', name: 'Newsprint', tagline: 'Morning-paper columns', category: 'Retro',
    bg: ['#ece5d3', '#d9cfb4'], cellBg: '#faf8f0',
    gap: 26, outerPad: 80, radius: 2, captionHeight: 120,
    captionFont: '700 40px Georgia, "Times New Roman", serif',
    captionColor: '#222222', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#ece5d3,#8a8271)',
    borderColor: '#8a8271', borderWidth: 2, shadow: false, pattern: 'stripes',
    placeholderColor: 'rgba(34,34,34,0.4)',
  },
  noir: {
    id: 'noir', name: 'Noir Cinema', tagline: 'Black-bar movie stills', category: 'Dark',
    bg: ['#000000', '#161616'], cellBg: '#000000',
    gap: 34, outerPad: 64, radius: 2, captionHeight: 120,
    captionFont: '500 44px Helvetica, Arial, sans-serif',
    captionColor: '#e8e4d8', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#000000,#4d4d4d)',
    borderColor: '#333333', borderWidth: 2, shadow: false, pattern: 'none',
    placeholderColor: 'rgba(232,228,216,0.4)',
  },
  disco: {
    id: 'disco', name: 'Disco Fever', tagline: 'Mirror-ball purple', category: 'Playful',
    bg: ['#2b0a4e', '#7b2ff7', '#f107a3'], cellBg: '#14082b',
    gap: 32, outerPad: 80, radius: 20, captionHeight: 125,
    captionFont: '800 46px Verdana, system-ui, sans-serif',
    captionColor: '#ffd6f5', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#2b0a4e,#f107a3)',
    borderColor: '#c86bfa', borderWidth: 3, shadow: false, pattern: 'dots',
    placeholderColor: 'rgba(255,214,245,0.45)',
  },
  candy: {
    id: 'candy', name: 'Candy Pop', tagline: 'Bubblegum bright', category: 'Playful',
    bg: ['#ffe3ec', '#ffc2d8'], cellBg: '#ffffff',
    gap: 42, outerPad: 86, radius: 30, captionHeight: 130,
    captionFont: '800 48px "Comic Sans MS", "Chalkboard SE", cursive',
    captionColor: '#c2185b', captionBg: null,
    grain: false, vignette: false, jitterDeg: 1.2,
    swatch: 'linear-gradient(135deg,#ffc2d8,#ff5c9d)',
    borderColor: '#ff8fb8', borderWidth: 3, shadow: true, pattern: 'dots',
    placeholderColor: 'rgba(194,24,91,0.4)',
  },
  pastel: {
    id: 'pastel', name: 'Pastel Dream', tagline: 'Cloud-soft haze', category: 'Light',
    bg: ['#e6e6fa', '#cfe8ef', '#fde8ef'], cellBg: '#ffffff',
    gap: 48, outerPad: 100, radius: 26, captionHeight: 125,
    captionFont: 'italic 46px Georgia, serif',
    captionColor: '#6b6b8f', captionBg: null,
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#cfe8ef,#fde8ef)',
    borderColor: '#cfcfe8', borderWidth: 2, shadow: true, pattern: 'none',
    placeholderColor: 'rgba(107,107,143,0.4)',
  },
  bauhaus: {
    id: 'bauhaus', name: 'Bauhaus', tagline: 'Primary shapes only', category: 'Playful',
    bg: ['#f2efe6', '#e2dccb'], cellBg: '#ffffff',
    gap: 30, outerPad: 78, radius: 2, captionHeight: 120,
    captionFont: '800 44px Helvetica, Arial, sans-serif',
    captionColor: '#1a1a1a', captionBg: '#f2efe6',
    grain: false, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#e30613 33%,#f5d90a 33% 66%,#0066b3 66%)',
    borderColor: '#1a1a1a', borderWidth: 5, shadow: false, pattern: 'none',
    placeholderColor: 'rgba(26,26,26,0.4)',
  },
  chalkboard: {
    id: 'chalkboard', name: 'Chalkboard', tagline: 'Classroom chalk dust', category: 'Dark',
    bg: ['#1e2b26', '#2e4038'], cellBg: '#223028',
    gap: 36, outerPad: 84, radius: 8, captionHeight: 130,
    captionFont: '52px "Comic Sans MS", "Segoe Print", cursive',
    captionColor: '#f5f2e4', captionBg: null,
    grain: true, vignette: false, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#1e2b26,#7fa393)',
    borderColor: '#c9a86a', borderWidth: 6, shadow: false, pattern: 'none',
    placeholderColor: 'rgba(245,242,228,0.4)',
  },
  golden: {
    id: 'golden', name: 'Golden Hour', tagline: 'Warm sunset glow', category: 'Nature',
    bg: ['#3a1c4f', '#c96f2f', '#f2b544'], cellBg: '#1f1029',
    gap: 34, outerPad: 84, radius: 18, captionHeight: 125,
    captionFont: 'italic 48px Georgia, serif',
    captionColor: '#ffe3a3', captionBg: null,
    grain: true, vignette: true, jitterDeg: 0,
    swatch: 'linear-gradient(135deg,#3a1c4f,#f2b544)',
    borderColor: '#e8a33d', borderWidth: 2, shadow: false, pattern: 'none',
    placeholderColor: 'rgba(255,227,163,0.45)',
  },
};

export const THEME_LIST: Theme[] = [
  THEMES.darkroom, THEMES.polaroid, THEMES.gallery, THEMES.y2k, THEMES.playground,
  THEMES['midnight-neon'], THEMES.espresso, THEMES.forest, THEMES.ocean, THEMES.desert,
  THEMES.sakura, THEMES['mono-ink'], THEMES.blueprint, THEMES.newsprint, THEMES.noir,
  THEMES.disco, THEMES.candy, THEMES.pastel, THEMES.bauhaus, THEMES.chalkboard, THEMES.golden,
];

export const THEME_CATEGORIES = ['All', 'Dark', 'Light', 'Retro', 'Playful', 'Elegant', 'Nature'] as const;
export type ThemeCategoryFilter = (typeof THEME_CATEGORIES)[number];
